# Shared helpers for corpus-profile build scripts.
#
# Sourced by the per-corpus drivers in corpora/ (wikipedia.sh, and whatever comes next --
# common crawl, etc). Everything corpus-agnostic lives here: directory layout, locating the
# textsearch CLI, rendering a fit config, and running the fit. A new corpus driver only has
# to implement "fetch raw files" and "turn them into JSONL", then call ts_fit.
#
# shellcheck shell=bash

set -euo pipefail

# These scripts use bash-only features (BASH_SOURCE, mapfile, [[ ]]); fail loudly rather
# than misbehave when sourced from another shell.
[ -n "${BASH_VERSION:-}" ] || {
  echo "error: corpus-profiles scripts require bash (run them directly, or 'bash -c ...')" >&2
  return 1 2>/dev/null || exit 1
}

CP_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPO_ROOT="$(cd "$CP_ROOT/.." && pwd)"
APP_DIR="$REPO_ROOT/apps/textsearch"

# Everything below is gitignored (see corpus-profiles/.gitignore): raw downloads, the
# intermediate JSONL, and the fitted profiles. Only scripts/configs are tracked.
RAW_DIR="${CP_ROOT_RAW_DIR:-$CP_ROOT/raw}"
WORK_DIR="${CP_ROOT_WORK_DIR:-$CP_ROOT/work}"
PROFILES_DIR="${CP_ROOT_PROFILES_DIR:-$CP_ROOT/profiles}"

log()  { printf '[%s] %s\n' "$(date +%H:%M:%S)" "$*" >&2; }
die()  { printf 'error: %s\n' "$*" >&2; exit 1; }

require_cmd() {
  for c in "$@"; do
    command -v "$c" >/dev/null 2>&1 || die "required command not found: $c"
  done
}

# ── the textsearch CLI ───────────────────────────────────────────────────────
#
# Prefer an installed `textsearch` executable (`julia -e 'using Pkg; pkg"app develop
# apps/textsearch"'`), otherwise fall back to running the app from this checkout so these
# scripts work without installing anything.

ts_cli() {
  if command -v textsearch >/dev/null 2>&1; then
    JULIA_NUM_THREADS="${JULIA_NUM_THREADS:-auto}" textsearch "$@"
  else
    julia --project="$APP_DIR" -t "${JULIA_NUM_THREADS:-auto}" "$APP_DIR/src/main.jl" "$@"
  fi
}

# Run a Julia helper script from lib/ inside the app's environment (so it can use the app's
# Parquet2/JSON3/TextSearch deps without a separate project).
ts_julia() {
  julia --project="$APP_DIR" -t "${JULIA_NUM_THREADS:-auto}" "$@"
}

# ── fit config rendering ─────────────────────────────────────────────────────

# ts_render_fit_config <out.toml>
#
# Writes a `textsearch fit --config` TOML from the TS_* variables below. Named variables
# rather than positional arguments on purpose: this grew past a dozen fields, and at that
# size a positional call is impossible to read and trivial to mis-order.
#
# Required: TS_JSONL TS_OUTDIR TS_PREFIX TS_BATCH
# Optional (defaults shown): everything else.
ts_render_fit_config() {
  local out="$1"
  : "${TS_JSONL:?ts_render_fit_config: TS_JSONL not set}"
  : "${TS_OUTDIR:?ts_render_fit_config: TS_OUTDIR not set}"
  : "${TS_PREFIX:?ts_render_fit_config: TS_PREFIX not set}"
  : "${TS_BATCH:?ts_render_fit_config: TS_BATCH not set}"

  local resume="${TS_RESUME:-false}"
  local text_key="${TS_TEXT_KEY:-text}"
  local fmt="${TS_FORMAT:-jsonl}"
  local min_ndocs="${TS_MIN_NDOCS:-5}"
  local sw_enabled="${TS_STOPWORDS:-true}"
  local sw_thresh="${TS_DOC_FREQ_THRESHOLD:-0.5}"
  local outdim="${TS_OUTDIM:-128}"
  local syn_k="${TS_SYN_K:-8}"
  local lem_alg="${TS_LEMMA_ALG:-fft}"
  local lem_sel="${TS_LEMMA_SEL:-most_frequent}"

  mkdir -p "$(dirname "$out")"
  cat > "$out" << EOF
# Generated by corpus-profiles scripts -- do not edit by hand; change the driver instead.
# Rendered $(date -Iseconds)

[input]
format = "$fmt"
path = "$TS_JSONL"
text_key = "$text_key"

[output]
dir = "$TS_OUTDIR"
prefix = "$TS_PREFIX"
batch_size = $TS_BATCH
resume = $resume

[normalization]
del_diac = true
del_dup = false
del_punc = false
group_num = true
group_url = true
group_usr = false
group_emo = false
lc = true

[tokenization]
nlist = [1]
mark_token_type = true

[vocabulary]
min_ndocs = $min_ndocs

[stopwords]
enabled = $sw_enabled
doc_freq_threshold = $sw_thresh

[encoder]
kind = "lsi"
outdim = $outdim
scaling = "none"
external_path = ""
factorization = "auto"

[synonyms]
k = $syn_k
approx = "auto"
construction_recall = 0.97
search_recall = 0.9

[lemmas]
algorithm = "$lem_alg"
num_clusters = 0
selector = "$lem_sel"
morphology = "jaccard"
morphology_threshold = 0.3
qgram = 2
min_common_prefix = 3
order = "morphology_first"
semantic_threshold = 1.0
EOF
  log "rendered fit config -> $out"
}

# ts_fit <config.toml>
ts_fit() {
  local cfg="$1"
  log "running: textsearch fit --config $cfg"
  ts_cli fit --config "$cfg"
}
